name: Suman King
favicon: null
layout_spectrum: 0.6944102514535189
typography_spectrum: 0.12710563256405294
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6319408514536917
  lightness: 0.6876087710261345
  saturation: 0.7246700720861554
  rhythmicContrast: 0.7215575573500246
purpose: []
