title: Lux Social Group
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 1
  lightness: 0
  brandColors:
    - '#121212'
    - '#FFFFFF'
    - '#54595F'
    - '#A9B0B8'
    - '#87949D'
  rhythmicContrast: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Suman King
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.2361702
layout_spectrum: 0.1468085
